# Build haxelib server as a Docker container.
# Note that it doesn't contain a MySQL database, 
# which need to be launched seperately. See test/docker-compose.yml on how to launch one.

FROM ubuntu:trusty

# apt-get dependencies of bower
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python-software-properties software-properties-common \
	&& add-apt-repository ppa:haxe/snapshots -y \
	&& apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
		apache2 \
		neko-dev \
		haxe \
		npm \
		nodejs-legacy \
		git \
		libcurl4-gnutls-dev \
	&& rm -r /var/lib/apt/lists/*

# apache httpd
RUN rm -rf /var/www/html \
	&& mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html \
	&& chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html 
RUN a2enmod rewrite
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist && rm /etc/apache2/conf-enabled/* /etc/apache2/sites-enabled/*
COPY apache2.conf /etc/apache2/apache2.conf
RUN { \
		echo 'LoadModule neko_module /usr/lib/x86_64-linux-gnu/neko/mod_neko2.ndll'; \
		echo 'LoadModule tora_module /usr/lib/x86_64-linux-gnu/neko/mod_tora2.ndll'; \
		echo 'AddHandler tora-handler .n'; \
	} > /etc/apache2/mods-enabled/tora.conf \
	&& apachectl stop

RUN mkdir -p /var/www/html
RUN echo 'RewriteBase /'								>> /var/www/html/.htaccess && \
	echo 'RewriteCond %{REQUEST_FILENAME} !-d'			>> /var/www/html/.htaccess && \
	echo 'RewriteCond %{REQUEST_FILENAME} !-f'			>> /var/www/html/.htaccess && \
	echo 'RewriteRule ^(.*)$ api/3.0/index.n/$1 [L]'	>> /var/www/html/.htaccess

RUN echo 'RewriteEngine On'		>> /etc/apache2/apache2.conf

# haxelib
ENV HAXELIB_PATH /haxelib
RUN mkdir "$HAXELIB_PATH" && haxelib setup "$HAXELIB_PATH" \
	&& haxelib install tora 1.8.1


RUN mkdir /src

COPY server_proxy.hxml /src/

WORKDIR /src
RUN haxelib install all --always
RUN cp ${HAXELIB_PATH}/aws-sdk-neko/*/ndll/Linux64/aws.ndll /usr/lib/x86_64-linux-gnu/neko/aws.ndll;

WORKDIR /src/www

COPY www/api /src/www/api
COPY www/files /src/www/files
COPY www/tmp /src/www/tmp
COPY src /src/src/

RUN mkdir -p /var/www/html/api
RUN mkdir -p /var/www/html/files
RUN mkdir -p /var/www/html/tmp

WORKDIR /src

RUN haxe server_proxy.hxml

RUN mv /src/www/api/* /var/www/html/api

ENV PARENT_SERVER http://lib.haxe.org

EXPOSE 80
VOLUME ["/var/www/html/files", "/var/www/html/tmp"]

WORKDIR /var/www/html/api/3.0

#CMD nekotools server -h 0.0.0.0 -p 80 -d . -rewrite -log log.log > /dev/null
CMD apachectl restart && haxelib run tora