branch-defaults:
  development:
    environment: development-lib-haxe-org
  master:
    environment: master-lib-haxe-org
deploy:
  artifact: eb.zip
environment-defaults:
  development-lib-haxe-org:
    branch: null
    repository: null
global:
  application_name: lib.haxe.org
  default_ec2_keyname: Andy-key-pair-eu-west
  default_platform: Docker running on 64bit Amazon Linux
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
